# Generated by Django 6.0.4 on 2026-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyecto', '0002_comentariotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='imagen_adjunta',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/imagenes/'),
        ),
    ]
