# Generated by Django 6.0.4 on 2026-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyecto', '0003_entrega_archivo_adjunto_entrega_imagen_adjunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='comentario_docente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
