# Generated by Django 6.0.4 on 2026-04-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyecto', '0004_entrega_comentario_docente_entrega_estado_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='estado_revision',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='imagen_adjunta',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='revisado_en',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='comentario_docente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
