# Generated by Django 6.0.4 on 2026-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyecto', '0005_remove_entrega_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='logros_obtenidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_lo_tienen', to='miProyecto.logro'),
        ),
    ]
